### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by keeqler** [NicolasLopes7/always-live-backend#1]
It's currently possible to add any kind of text other than an URL, validating would be cool.

**Comment by NKKFu** [comment]
> It's currently possible to add any kind of text other than an URL, validating would be cool.

I also noticed this and it is really important, even dangerous to not have this type of validation.

**Comment by NicolasLopes7** [comment]
Good point. I did it yesterday very quickly, I will add the validation. Thank you

**Comment by NicolasLopes7** [comment]
Good point. I did it yesterday very quickly, I will add the validation. Thank you
